name: Clang Formatter
on: workflow_dispatch
jobs:
  Job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install clang-format
        run: sudo apt-get install clang-format -y

      - name: Formatting files
        run: find ./project/discord-rpc -name '*.c' -o -name '*.cpp' -o -name '*.m' -o -name '*.mm' -o -name '*.h' -o -name '*.hpp' | xargs clang-format -i

      - name: Verify Formatting
        run: git status --short

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: formattedFiles
          path: ./project/discord-rpc
          if-no-files-found: error
